# Etapa 1: Construir la aplicación (Maven con Temurin Java 21)
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copiamos los archivos necesarios
COPY pom.xml .
COPY src ./src

# Compilamos el proyecto
RUN mvn clean package -DskipTests

# Etapa 2: Ejecutar la aplicación
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

# Cambiamos el *.jar por app.jar (que definimos en el pom.xml)
COPY --from=build /app/target/app.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]