# Etapa 1: Construir la aplicación (Maven)
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app

# Copiamos los archivos de configuración y el código
COPY pom.xml .
COPY src ./src

# Compilamos y generamos el archivo JAR
RUN mvn clean package -DskipTests

# Etapa 2: Ejecutar la aplicación (Java Runtime)
FROM openjdk:17-jdk-slim
WORKDIR /app

# Traemos el archivo generado desde la etapa de construcción
COPY --from=build /app/target/*.jar app.jar

# Exponemos el puerto que usa Spring Boot
EXPOSE 8080

# Comando para arrancar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]